name: Go Lint

on:
  pull_request:

jobs:
  golangci:
    name: golangci-Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scheduler-engine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: scheduler-engine/go.mod
          cache: true
      
      - name: Run golangci-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m